#pragma once


#include <acx/strings.h>


namespace accounting {


  // ===== Domain =====

  SCSTR ERROR_CURRENCY_INVALID = "Error. Invalid currency value.";

  SCSTR CURRENCY_SHORT_USD = "USD";
  SCSTR CURRENCY_SHORT_MYR = "MYR";
  SCSTR CURRENCY_SHORT_BYN = "BYN";
  SCSTR CURRENCY_SHORT_NONE = "none";

  SCSTR CURRENCY_FULL_USD = "US Dollars";
  SCSTR CURRENCY_FULL_MYR = "Malaysian Ringgits";
  SCSTR CURRENCY_FULL_BYN = "Belarussian Rubles";
  SCSTR CURRENCY_FULL_NONE = "No currency";

  SCSTR ERROR_ACCOUNT_TYPE_INVALID = "Error. Invalid account type value.";

  SCSTR ACCOUNT_TYPE_PASSIVE = "passive";
  SCSTR ACCOUNT_TYPE_ACTIVE = "active";
  SCSTR ACCOUNT_TYPE_NONE = "none";


  // ===== JSON =====

  SCSTR JSON_NULL = "null";

  SCSTR JSON_ACCOUNT_ID_KEY = "id";
  SCSTR JSON_ACCOUNT_NAME_KEY = "name";
  SCSTR JSON_ACCOUNT_BALANCE_KEY = "balance";
  SCSTR JSON_ACCOUNT_TYPE_KEY = "type";
  SCSTR JSON_ACCOUNT_CURRENCY_KEY = "currency";

  SCSTR JSON_TRANSFER_STATE_SWITCH_VALIDATED_KEY = "validated";
  SCSTR JSON_TRANSFER_STATE_SWITCH_STARTED_KEY = "started";
  SCSTR JSON_TRANSFER_STATE_SWITCH_CREDIT_DECREASED_KEY = "credit_decreased";
  SCSTR JSON_TRANSFER_STATE_SWITCH_DEBIT_INCREASED_KEY = "debit_increased";
  SCSTR JSON_TRANSFER_STATE_SWITCH_FINISHED_KEY = "finished";
  SCSTR JSON_TRANSFER_STATE_SWITCH_INTERRUPTED_KEY = "interrupted";

  SCSTR JSON_TRANSFER_ID_KEY = "id";
  SCSTR JSON_TRANSFER_DATE_TIME_KEY = "date_time";
  SCSTR JSON_TRANSFER_CONVERSION_RATE_KEY = "conversion_rate";
  SCSTR JSON_TRANSFER_STATE_KEY = "state";
  SCSTR JSON_TRANSFER_ERR_MSG_KEY = "err_msg";
  SCSTR JSON_TRANSFER_DEBIT_ACCOUNT_KEY = "debit_account";
  SCSTR JSON_TRANSFER_DEBIT_AMOUNT_KEY = "debit_amount";
  SCSTR JSON_TRANSFER_CREDIT_ACCOUNT_KEY = "credit_account";
  SCSTR JSON_TRANSFER_CREDIT_AMOUNT_KEY = "credit_amount";


}
