#pragma once


#define JSON_NULL "null"

#define JSON_ACCOUNT_ID_KEY "id"
#define JSON_ACCOUNT_NAME_KEY "name"
#define JSON_ACCOUNT_BALANCE_KEY "balance"
#define JSON_ACCOUNT_TYPE_KEY "type"
#define JSON_ACCOUNT_CURRENCY_KEY "currency"

#define JSON_TRANSFER_STATE_SWITCH_VALIDATED_KEY "validated"
#define JSON_TRANSFER_STATE_SWITCH_STARTED_KEY "started"
#define JSON_TRANSFER_STATE_SWITCH_CREDIT_DECREASED_KEY "credit_decreased"
#define JSON_TRANSFER_STATE_SWITCH_DEBIT_INCREASED_KEY "debit_increased"
#define JSON_TRANSFER_STATE_SWITCH_FINISHED_KEY "finished"
#define JSON_TRANSFER_STATE_SWITCH_INTERRUPTED_KEY "interrupted"

#define JSON_TRANSFER_ID_KEY "id"
#define JSON_TRANSFER_DATE_TIME_KEY "date_time"
#define JSON_TRANSFER_CONVERSION_RATE_KEY "conversion_rate"
#define JSON_TRANSFER_STATE_KEY "state"
#define JSON_TRANSFER_ERR_MSG_KEY "err_msg"
#define JSON_TRANSFER_DEBIT_ACCOUNT_KEY "debit_account"
#define JSON_TRANSFER_DEBIT_AMOUNT_KEY "debit_amount"
#define JSON_TRANSFER_CREDIT_ACCOUNT_KEY "credit_account"
#define JSON_TRANSFER_CREDIT_AMOUNT_KEY "credit_amount"

